# Generated by Django 5.0.6 on 2024-05-17 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobapplication',
            name='experience',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='references',
            field=models.JSONField(default=list),
        ),
    ]
