# Generated by Django 4.2.5 on 2024-05-08 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='logo',
            field=models.CharField(max_length=9999),
        ),
    ]
