# Generated by Django 4.2.5 on 2024-05-08 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_alter_company_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='year_of_start',
            field=models.DateField(),
        ),
    ]
