# Generated by Django 5.0.4 on 2024-05-13 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0004_companyimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='logo',
            field=models.ImageField(upload_to=''),
        ),
        migrations.DeleteModel(
            name='CompanyImage',
        ),
    ]
