# Generated by Django 5.0.6 on 2024-05-15 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0005_alter_company_logo_delete_companyimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
