# Generated by Django 5.0.6 on 2024-05-17 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0006_company_cover_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='cover_images/'),
        ),
        migrations.AlterField(
            model_name='company',
            name='logo',
            field=models.ImageField(upload_to='logos/'),
        ),
    ]
