# Generated by Django 5.0.4 on 2024-05-16 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0007_remove_company_cover_image_alter_company_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='picture',
            field=models.ImageField(default='hekla-logo.png', upload_to='media'),
        ),
    ]
