# Generated by Django 5.0.4 on 2024-05-16 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0008_company_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='picture',
            field=models.ImageField(default='hekla-logo.png', upload_to='media'),
        ),
    ]
