# Generated by Django 5.0.6 on 2024-05-17 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0007_alter_company_cover_image_alter_company_logo'),
        ('company', '0009_alter_company_picture'),
    ]

    operations = [
    ]
