# Generated by Django 4.2.5 on 2024-05-08 00:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='date_expired',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='date_offer',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
