# Generated by Django 5.0.4 on 2024-05-13 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0002_job_date_expired_job_date_offer'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='full_part_time',
            field=models.CharField(default='Full time', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='job',
            name='location',
            field=models.CharField(default='Reykjavík', max_length=255),
            preserve_default=False,
        ),
    ]
